### ISSUE TITLE
Migrate to GitLab

### ISSUE THREAD

**Issue by brlin-tw** [the-common/markdownlint-nodejs-config-templates#1]
## Tasks

* [ ] Import project to GitLab
* [ ] Disable Issues/Wiki/Projects functionality in the GitHub repository
* [ ] Update project reference in README
* [ ] Update project reference in GitHub repository metadata
